def reverse_shell_list():
    print("")
    print("- [Reverse Shell Type] -")
    print("_____________________________________")
    print("|ID   |       Reverse Shell          |")
    print("|=====+==============================+")
    print("| 1   |      bash -i TCP             |")
    print("| 2   |      bash -i UDP             |")
    print("| 3   |      nc -c                   |")
    print("| 4   |      nc -e                   |")
    print("| 5   |      nc mkfifo               |")
    print("| 6   |      perl                    |")
    print("| 7   |      python3                 |")
    print("| 8   |      php exec                |")
    print("| 9   |      php shell exec          |")
    print("| 10  |      php `                   |")
    print("| 11  |      php system              |")
    print("| 12  |      php passthru            |")
    print("| 13  |      php popen               |")
    print("| 14  |      ruby                    |")
    print("+-----+------------------------------+")
