def reverse_shell_list():
    print("")
    print("- [Reverse Shell Type] -")
    print("_____________________________________")
    print("|ID   |       Reverse Shell          |")
    print("|=====+==============================+")
    print("| 1   |       bash -i TCP            |")
    print("| 2   |       bash -i UDP            |")
    print("| 3   |       nc -c                  |")
    print("| 4   |       nc -e                  |")
    print("| 5   |       nc mkfifo              |")
    print("| 6   |       perl                   |")
    print("| 7   |       python3                |")
    print("+-----+------------------------------+")
